version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
    depends_on:
      - db
    networks:
      - app-network
    tty: true

  db:
    image: mysql:8.0
    container_name: ap4db
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ap4
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:

